/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.sql.Connection
import java.sql.SQLException
import java.sql.DriverManager

fun connectToDatabase(): Connection? {
    val url = "jdbc:mysql://localhost:3306/Test01DB?useTimezone=true&serverTimezone=America/New_York"
    val user = "root"
    val password = "dummypass"

    return try {
        DriverManager.getConnection(url, user, password)
    } catch (e: SQLException) {
        println( e )
        null
    }
}

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

    var conn = connectToDatabase();

    if ( conn != null ) {

        val query = conn.prepareStatement("Select * From sysUserGroup")

        // the query is executed and results are fetched
        val result = query.executeQuery()

        while(result.next()){

            // getting the value of the id column
            val id = result.getString("Id")
    
            // getting the value of the name column
            val name = result.getString("Name")
    
            println("Id: " + id + ", Name: " + name )
            /*
            constructing a User object and
            putting data into the list
             */
            //users.add(User(id, name))
        }        

    }

}
